### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/tcam#1]
- [ ] cover the rest of the tCam-Mini API
- [ ] add conversion for rasters and {magick}
- [ ] enable callers to specify temperature units
- [ ] convert other data structure elements
- [ ] add some fancy histograms and other flare
- [ ] [STRETCH] Shiny app to support image streaming/capture.

**Comment by McGeaverBeaver** [comment]
[STRETCH] Shiny app to support image streaming/capture. 

This would be insane!!  Thank you for all the work you put into this with Dan!
